# Generated by Django 3.0.8 on 2020-09-24 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('line_type', models.CharField(choices=[('R', 'Restaurant'), ('B', 'Bar'), ('C', 'Club'), ('W', 'Recreational'), ('T', 'Thrill Ride'), ('S', 'Retail Store'), ('O', 'Other')], default='R', max_length=1)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Yelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait_time', models.IntegerField()),
                ('party_size', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lines.Line')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lines.Line')),
            ],
        ),
    ]
