# Generated by Django 3.1.1 on 2020-09-19 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_auto_20200919_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='line',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='line',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='line',
            name='is_open',
        ),
        migrations.AlterField(
            model_name='line',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='line',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='line',
            name='stars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lines.line')),
            ],
        ),
    ]
