# Generated by Django 3.1.1 on 2020-09-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0003_auto_20200919_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
