# Generated by Django 3.1.1 on 2020-09-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0004_auto_20200919_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='user_id',
            new_name='user',
        ),
    ]
