# Generated by Django 3.1.1 on 2020-09-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0005_auto_20200919_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='stars',
        ),
        migrations.AddField(
            model_name='line',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
