# Generated by Django 2.2.12 on 2020-09-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0007_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='wait',
            name='line',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lines.Line'),
            preserve_default=False,
        ),
    ]
