# Generated by Django 3.1.1 on 2020-09-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0008_wait_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wait',
            name='business_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
