# Generated by Django 3.1.1 on 2020-09-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0010_auto_20200921_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wait',
            name='business_id',
        ),
    ]
