# Generated by Django 3.1.1 on 2020-09-23 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0011_remove_wait_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wait',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='line',
            name='line_type',
            field=models.CharField(choices=[('R', 'Restaurant'), ('B', 'Bar'), ('C', 'Club'), ('W', 'Recreational'), ('T', 'Thrill Ride'), ('S', 'Retail Store'), ('O', 'Other')], default='R', max_length=1),
        ),
    ]
