# Generated by Django 3.1.1 on 2020-09-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0012_auto_20200923_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yelp',
            name='id',
        ),
        migrations.AlterField(
            model_name='yelp',
            name='business_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
