# Generated by Django 3.1.1 on 2020-09-24 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0013_auto_20200924_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='wait',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lines.yelp'),
        ),
    ]
