# Generated by Django 3.1.1 on 2020-09-24 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0014_wait_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wait',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lines.line'),
        ),
    ]
